apiVersion: v1
kind: Service
metadata:
  name: user-rest-api-service
spec:
  type: LoadBalancer
  selector:
    app:  user-rest-api
  ports:
    - port: 5000  # Port your service listens on inside the cluster
      targetPort: 5000  # Port your application is listening on
